environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
#

build_script:
  - gradlew :common:downloadFiraCode --info --warning-mode=all
  - gradlew :swing:fatJar --info --warning-mode=all
#

artifacts:
  - path: 'swing\build\libs\*.jar'
    name: snapshot
#
